import * as fs from 'fs';
import * as path from 'path';

function generateEmail(name: string): string {
  const cleanName = name.trim().toLowerCase().replace(/\s+/g, ' ');
  const parts = cleanName.split(' ');
  if (parts.length === 1) return `${parts[0]}.${parts[0]}@mca.christuniversity.in`;
  return `${parts[0]}.${parts[parts.length - 1]}@mca.christuniversity.in`;
}

function dryRun() {
  const csvFilePath = path.resolve(process.cwd(), 'students.csv');
  const fileContent = fs.readFileSync(csvFilePath, 'utf-8');
  const lines = fileContent.split('\n').map(line => line.trim()).filter(line => line.length > 0);
  
  let totalRows = lines.length - 1; // excluding header
  let validRows = 0;
  let invalidRows = 0;
  let autoGeneratedEmails = 0;
  
  const emailsSeen = new Set<string>();
  let duplicateEmails = 0;
  
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split(',');
    const register_number = cols[0]?.trim();
    const student_name = cols[1]?.trim();
    const raw_email = cols.slice(2).join(',').trim();
    
    if (!register_number || !student_name) {
      invalidRows++;
      continue;
    }
    
    validRows++;
    
    let finalEmail = raw_email.toLowerCase().replace(/\s+/g, '');
    if (!finalEmail) {
      finalEmail = generateEmail(student_name);
      autoGeneratedEmails++;
    }
    
    if (emailsSeen.has(finalEmail)) {
      duplicateEmails++;
    } else {
      emailsSeen.add(finalEmail);
    }
  }
  
  console.log(`Dry Run Results:`);
  console.log(`Total rows: ${totalRows}`);
  console.log(`Valid rows: ${validRows}`);
  console.log(`Invalid rows: ${invalidRows}`);
  console.log(`Duplicate emails: ${duplicateEmails}`);
  console.log(`Auto-generated emails: ${autoGeneratedEmails}`);
}

dryRun();
