import { readdirSync, statSync } from "fs";
import { join, relative } from "path";

const friendTree = new Set([
  ".env",
  ".env.example",
  ".env.local",
  ".lovable/project.json",
  ".prettierignore",
  ".prettierrc",
  "README.md",
  "acadsphere",
  "bun.lock",
  "bunfig.toml",
  "components.json",
  "cue-extension/README.md",
  "cue-extension/content.js",
  "cue-extension/manifest.json",
  "cue-extension/popup.html",
  "cue-extension/popup.js",
  "database_setup_guide.md",
  "eslint.config.js",
  "extract_text.py",
  "import-report.csv",
  "package-lock.json",
  "package.json",
  "public/robots.txt",
  "requirements.txt",
  "scratch/export_emails.mjs",
  "scratch/student_emails.txt",
  "scratch/test-cue-login.js",
  "scripts/demo-sms-payload.json",
  "scripts/dry-run.ts",
  "scripts/import-students.ts",
  "scripts/seed-mca-students.js",
  "scripts/test-demo-sms.ps1",
  "scripts/test-supabase.ts",
  "scripts/verify-import.ts",
  "src/assets/studentos-logo.png",
  "src/components/admin/AdminLayout.tsx",
  "src/components/ai-elements/conversation.tsx",
  "src/components/ai-elements/message.tsx",
  "src/components/ai-elements/prompt-input.tsx",
  "src/components/ai-elements/shimmer.tsx",
  "src/components/chat/AcademicCopilot.tsx",
  "src/components/chat/ChatLayout.tsx",
  "src/components/chat/ChatWindow.tsx",
  "src/components/ui/accordion.tsx",
  "src/components/ui/alert-dialog.tsx",
  "src/components/ui/alert.tsx",
  "src/components/ui/aspect-ratio.tsx",
  "src/components/ui/avatar.tsx",
  "src/components/ui/badge.tsx",
  "src/components/ui/breadcrumb.tsx",
  "src/components/ui/button-group.tsx",
  "src/components/ui/button.tsx",
  "src/components/ui/calendar.tsx",
  "src/components/ui/card.tsx",
  "src/components/ui/carousel.tsx",
  "src/components/ui/chart.tsx",
  "src/components/ui/checkbox.tsx",
  "src/components/ui/collapsible.tsx",
  "src/components/ui/command.tsx",
  "src/components/ui/context-menu.tsx",
  "src/components/ui/dialog.tsx",
  "src/components/ui/drawer.tsx",
  "src/components/ui/dropdown-menu.tsx",
  "src/components/ui/form.tsx",
  "src/components/ui/hover-card.tsx",
  "src/components/ui/input-group.tsx",
  "src/components/ui/input-otp.tsx",
  "src/components/ui/input.tsx",
  "src/components/ui/label.tsx",
  "src/components/ui/menubar.tsx",
  "src/components/ui/navigation-menu.tsx",
  "src/components/ui/pagination.tsx",
  "src/components/ui/popover.tsx",
  "src/components/ui/progress.tsx",
  "src/components/ui/radio-group.tsx",
  "src/components/ui/resizable.tsx",
  "src/components/ui/scroll-area.tsx",
  "src/components/ui/select.tsx",
  "src/components/ui/separator.tsx",
  "src/components/ui/sheet.tsx",
  "src/components/ui/sidebar.tsx",
  "src/components/ui/skeleton.tsx",
  "src/components/ui/slider.tsx",
  "src/components/ui/sonner.tsx",
  "src/components/ui/spinner.tsx",
  "src/components/ui/switch.tsx",
  "src/components/ui/table.tsx",
  "src/components/ui/tabs.tsx",
  "src/components/ui/textarea.tsx",
  "src/components/ui/toggle-group.tsx",
  "src/components/ui/toggle.tsx",
  "src/components/ui/tooltip.tsx",
  "src/design-system/tokens.ts",
  "src/hooks/use-mobile.tsx",
  "src/hooks/useCopilot.ts",
  "src/integrations/lovable/index.ts",
  "src/integrations/supabase/auth-attacher.ts",
  "src/integrations/supabase/auth-middleware.ts",
  "src/integrations/supabase/client.server.ts",
  "src/integrations/supabase/client.ts",
  "src/integrations/supabase/supabase.server.ts",
  "src/integrations/supabase/types.ts",
  "src/lib/api/example.functions.ts",
  "src/lib/events/event.functions.ts",
  "src/lib/knowledge/knowledge.functions.ts",
  "src/lib/student-intelligence/student-intelligence.service.ts",
  "src/lib/student-metrics/student-metrics.functions.ts",
  "src/lib/academic-ai.engine.ts",
  "src/lib/admin-middleware.ts",
  "src/lib/admin.functions.ts",
  "src/lib/ai-gateway.server.ts",
  "src/lib/analytics.functions.ts",
  "src/lib/attendance-margins.ts",
  "src/lib/attendance.functions.ts",
  "src/lib/auth.functions.ts",
  "src/lib/chat.functions.ts",
  "src/lib/classroom.functions.ts",
  "src/lib/config.server.ts",
  "src/lib/db.server.ts",
  "src/lib/error-capture.ts",
  "src/lib/error-page.ts",
  "src/lib/lovable-error-reporting.ts",
  "src/lib/paper.functions.ts",
  "src/lib/resume.functions.ts",
  "src/lib/roadmap.functions.ts",
  "src/lib/settler.functions.ts",
  "src/lib/student-os-prompt.ts",
  "src/lib/studentos.functions.ts",
  "src/lib/study.functions.ts",
  "src/lib/utils.ts",
  "src/routes/_authenticated/app.$threadId.tsx",
  "src/routes/_authenticated/app.ai-assistant.tsx",
  "src/routes/_authenticated/app.announcements.tsx",
  "src/routes/_authenticated/app.assignments.tsx",
  "src/routes/_authenticated/app.attendance.tsx",
  "src/routes/_authenticated/app.career-roadmap.tsx",
  "src/routes/_authenticated/app.classroom.tsx",
  "src/routes/_authenticated/app.community.tsx",
  "src/routes/_authenticated/app.conversions.tsx",
  "src/routes/_authenticated/app.extra.tsx",
  "src/routes/_authenticated/app.index.tsx",
  "src/routes/_authenticated/app.profile.tsx",
  "src/routes/_authenticated/app.resume-analyzer.tsx",
  "src/routes/_authenticated/app.resume-builder.tsx",
  "src/routes/_authenticated/app.settings.tsx",
  "src/routes/_authenticated/app.students.tsx",
  "src/routes/_authenticated/paper-simplifier.tsx",
  "src/routes/_authenticated/route.tsx",
  "src/routes/admin/academic-monitoring.tsx",
  "src/routes/admin/analytics.tsx",
  "src/routes/admin/announcements.tsx",
  "src/routes/admin/audit-logs.tsx",
  "src/routes/admin/index.tsx",
  "src/routes/admin/live-activity.tsx",
  "src/routes/admin/reports.tsx",
  "src/routes/admin/roles.tsx",
  "src/routes/admin/route.tsx",
  "src/routes/admin/security.tsx",
  "src/routes/admin/settings.tsx",
  "src/routes/admin/students.tsx",
  "src/routes/admin/users.tsx",
  "src/routes/api/chat.ts",
  "src/routes/api/sync-attendance.ts",
  "src/routes/README.md",
  "src/routes/__root.tsx",
  "src/routes/auth.callback.tsx",
  "src/routes/auth.tsx",
  "src/routes/index.tsx",
  "src/routes/sitemap[.]xml.ts",
  "src/routeTree.gen.ts",
  "src/router.tsx",
  "src/server.ts",
  "src/start.ts",
  "src/styles.css",
  "students.csv",
  "supabase/config.toml",
  "supabase/functions/file-converter/index.ts",
  "supabase/functions/kp-scraper/index.ts",
  "supabase/functions/send-demo-sms/index.ts",
  "supabase/functions/send-sms-reminders/index.ts",
  "supabase/functions/sync-attendance/index.ts",
  "supabase/migrations/0000_initial_schema.sql",
  "supabase/migrations/0001_complete_schema.sql",
  "supabase/migrations/20260604051633_3845684d-e710-4e4a-87e5-cb829d372bbf.sql",
  "supabase/migrations/20260604051649_ed4c0743-a82e-49eb-9387-4c7033d90956.sql",
  "supabase/migrations/20260618000001_8b63c9db-0ff0-4fcd-b676-0529b8b07d69.sql",
  "supabase/migrations/20260618000002_7f3a9cb1-5c2f-46e1-9f0e-6df4b9c3e0a2.sql",
  "supabase/migrations/20260618000003_22f5c321-4e2d-4ed0-8fd3-7a23c6c4a9b1.sql",
  "supabase/migrations/20260623000000_studentos_premium_schema.sql",
  "supabase/migrations/20260801000001_sms_notifications_schema.sql",
  "supabase/migrations/20260801000002_pg_cron_schedule.sql",
  "supabase/migrations/20260803000001_conversions_bucket_rls.sql",
  "supabase/migrations/20260804000001_community_chat.sql",
  "supabase/migrations/20260805000001_add_author_initials_to_community_posts.sql",
  "supabase/migrations/20260805000002_get_all_students_fn.sql",
  "supabase/migrations/20260805000003_private_messages.sql",
  "supabase/migrations/20260807000001_create_student_attendance_table.sql",
  "supabase/migrations/20260812000001_create_direct_messages_table.sql",
  "tsconfig.json",
  "vercel.json",
  "vite.config.ts"
]);

const baseDir = process.cwd();

function getAllFiles(dir, fileList = []) {
  const files = readdirSync(dir);
  for (const file of files) {
    const filePath = join(dir, file);
    const relPath = relative(baseDir, filePath).replace(/\\/g, "/");

    // Ignore node_modules, .git, dist, .tanstack
    if (
      relPath.startsWith("node_modules") ||
      relPath.startsWith(".git") ||
      relPath.startsWith("dist") ||
      relPath.startsWith(".tanstack") ||
      relPath.startsWith("supabase/.temp")
    ) {
      continue;
    }

    const stat = statSync(filePath);
    if (stat.isDirectory()) {
      getAllFiles(filePath, fileList);
    } else {
      fileList.push(relPath);
    }
  }
  return fileList;
}

const localFiles = getAllFiles(baseDir);
const missingInFriendTree = [];

for (const f of localFiles) {
  if (!friendTree.has(f)) {
    missingInFriendTree.push(f);
  }
}

console.log("--- MISSING IN FRIEND'S TREE ---");
console.log(JSON.stringify(missingInFriendTree, null, 2));
