/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStudyPlannerRouteImport } from './routes/_authenticated/study-planner'
import { Route as AuthenticatedPaperSimplifierRouteImport } from './routes/_authenticated/paper-simplifier'
import { Route as AuthenticatedNotesGapAnalyzerRouteImport } from './routes/_authenticated/notes-gap-analyzer'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppResumeAnalyzerRouteImport } from './routes/_authenticated/app.resume-analyzer'
import { Route as AuthenticatedAppCareerRoadmapRouteImport } from './routes/_authenticated/app.career-roadmap'
import { Route as AuthenticatedAppThreadIdRouteImport } from './routes/_authenticated/app.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyPlannerRoute =
  AuthenticatedStudyPlannerRouteImport.update({
    id: '/study-planner',
    path: '/study-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaperSimplifierRoute =
  AuthenticatedPaperSimplifierRouteImport.update({
    id: '/paper-simplifier',
    path: '/paper-simplifier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesGapAnalyzerRoute =
  AuthenticatedNotesGapAnalyzerRouteImport.update({
    id: '/notes-gap-analyzer',
    path: '/notes-gap-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppResumeAnalyzerRoute =
  AuthenticatedAppResumeAnalyzerRouteImport.update({
    id: '/app/resume-analyzer',
    path: '/app/resume-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCareerRoadmapRoute =
  AuthenticatedAppCareerRoadmapRouteImport.update({
    id: '/app/career-roadmap',
    path: '/app/career-roadmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppThreadIdRoute =
  AuthenticatedAppThreadIdRouteImport.update({
    id: '/app/$threadId',
    path: '/app/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/notes-gap-analyzer': typeof AuthenticatedNotesGapAnalyzerRoute
  '/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/study-planner': typeof AuthenticatedStudyPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/notes-gap-analyzer': typeof AuthenticatedNotesGapAnalyzerRoute
  '/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/study-planner': typeof AuthenticatedStudyPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/notes-gap-analyzer': typeof AuthenticatedNotesGapAnalyzerRoute
  '/_authenticated/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/_authenticated/study-planner': typeof AuthenticatedStudyPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/_authenticated/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/_authenticated/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/notes-gap-analyzer'
    | '/paper-simplifier'
    | '/study-planner'
    | '/api/chat'
    | '/app/$threadId'
    | '/app/career-roadmap'
    | '/app/resume-analyzer'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/notes-gap-analyzer'
    | '/paper-simplifier'
    | '/study-planner'
    | '/api/chat'
    | '/app/$threadId'
    | '/app/career-roadmap'
    | '/app/resume-analyzer'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/notes-gap-analyzer'
    | '/_authenticated/paper-simplifier'
    | '/_authenticated/study-planner'
    | '/api/chat'
    | '/_authenticated/app/$threadId'
    | '/_authenticated/app/career-roadmap'
    | '/_authenticated/app/resume-analyzer'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study-planner': {
      id: '/_authenticated/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof AuthenticatedStudyPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paper-simplifier': {
      id: '/_authenticated/paper-simplifier'
      path: '/paper-simplifier'
      fullPath: '/paper-simplifier'
      preLoaderRoute: typeof AuthenticatedPaperSimplifierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes-gap-analyzer': {
      id: '/_authenticated/notes-gap-analyzer'
      path: '/notes-gap-analyzer'
      fullPath: '/notes-gap-analyzer'
      preLoaderRoute: typeof AuthenticatedNotesGapAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/resume-analyzer': {
      id: '/_authenticated/app/resume-analyzer'
      path: '/app/resume-analyzer'
      fullPath: '/app/resume-analyzer'
      preLoaderRoute: typeof AuthenticatedAppResumeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/career-roadmap': {
      id: '/_authenticated/app/career-roadmap'
      path: '/app/career-roadmap'
      fullPath: '/app/career-roadmap'
      preLoaderRoute: typeof AuthenticatedAppCareerRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$threadId': {
      id: '/_authenticated/app/$threadId'
      path: '/app/$threadId'
      fullPath: '/app/$threadId'
      preLoaderRoute: typeof AuthenticatedAppThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedNotesGapAnalyzerRoute: typeof AuthenticatedNotesGapAnalyzerRoute
  AuthenticatedPaperSimplifierRoute: typeof AuthenticatedPaperSimplifierRoute
  AuthenticatedStudyPlannerRoute: typeof AuthenticatedStudyPlannerRoute
  AuthenticatedAppThreadIdRoute: typeof AuthenticatedAppThreadIdRoute
  AuthenticatedAppCareerRoadmapRoute: typeof AuthenticatedAppCareerRoadmapRoute
  AuthenticatedAppResumeAnalyzerRoute: typeof AuthenticatedAppResumeAnalyzerRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedNotesGapAnalyzerRoute: AuthenticatedNotesGapAnalyzerRoute,
  AuthenticatedPaperSimplifierRoute: AuthenticatedPaperSimplifierRoute,
  AuthenticatedStudyPlannerRoute: AuthenticatedStudyPlannerRoute,
  AuthenticatedAppThreadIdRoute: AuthenticatedAppThreadIdRoute,
  AuthenticatedAppCareerRoadmapRoute: AuthenticatedAppCareerRoadmapRoute,
  AuthenticatedAppResumeAnalyzerRoute: AuthenticatedAppResumeAnalyzerRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
